#!/bin/sh

# Potential ENV vars, defaults are set in tag_server.app.src
# SESSION_COOKIE (ts_session)
# PORT (10100)
# CHASE_DOMAIN (chase.psiinteractive.com)

erl \
	-pa ebin \
	-pa deps/*/ebin \
	-config app \
	-s tag_server
